### ISSUE TITLE
Installation fails when install file doesn't exist

### ISSUE THREAD

**Issue by rmarquis** [polygamma/aurman#3] opened 2018-02-08 10:07 UTC
After a successful build, the package fails to install. I assume this happens only when the package doesn't have a `.install` file.

```
$ python main.py -Su
:: Starting full system upgrade...
 there is nothing to do
AUR Packages: nlohmann-json auracle-git
Repo Packages: 
Do you want to install these packages? Y/n: y
Do you want to view the changes of PKGBUILD of nlohmann-json ? N/y: y
Do you want to edit PKGBUILD? N/y: y
Do you want to use the files as they are now? Y/n: y
==> Making package: nlohmann-json 3.1.0-1 (Thu  8 Feb 10:31:52 CET 2018)
....
==> Cleaning up...
2018-02-08 10:38:59,298 - package_classes - install - ERROR - install file of nlohmann-json not available
2018-02-08 10:38:59,298 - main - <module> - ERROR - Unknown exception occurred.
Traceback (most recent call last):
  File "main.py", line 167, in <module>
    process(argv[1:])
  File "main.py", line 162, in process
    package.install(args_with_asdeps)
  File "/home/remy/code/aurman/src/package_classes.py", line 134, in install
    raise InvalidInput()
own_exceptions.InvalidInput
```

**Comment by polygamma** [comment] 2018-02-08 10:15
Calling it "install file" was bad. Meant are the package files you want to install with -U.
Are you using the current master branch? If not, this is relevant: https://github.com/polygamma/aurman/commit/e3f9f7f705a8dda7f4b75225950a802b798f46be

If you are using it, what is the name of built package file in the .cache/aurman/nlohmann-json folder?

**Comment by rmarquis** [comment] 2018-02-08 10:25
Yes, I'm on 0.33 - just 2 commit nehing before your fix. I'd indeed suggested to change the name to something like "built package".

I have defined $PKGDEST in my `makepkg.conf`, and I am also using `pacman-git`. The current version of pacman install a symlink in the build folder to the real location of the file, but pacman-git doesn't anymore. For now, you'll need to check PKGDEST manually, but a patch in the [pacman-dev ML](https://lists.archlinux.org/pipermail/pacman-dev/2018-February/022284.html) will soon be available in the pacman master branch.

Without $PKGDEST defined, the package installs correctly. 

I'd also suggest to use pacman-git too. The release is not too far away, and some changes might be relevant to helper.

**Comment by polygamma** [comment] 2018-02-08 10:47
Thank you very much, going to fix it soon.

**Comment by polygamma** [comment] 2018-02-08 11:22
fixed in: https://github.com/polygamma/aurman/commit/2c731a2b841aa93341966251fc19e3a5341bf88a

**Closed** 2018-02-08 11:22 UTC

**Comment by SamHH** [comment] 2018-06-20 12:14
I appear to be getting this same error now with one particular package.

```~~ initializing aurman...
~~ calculating solutions...

:: The following 1 package(s) are getting installed:
   aur/rofi-greenclip  /  ->  3.0-0

?? Do you want to continue? Y/n: 
~~ looking for new pkgbuilds and fetching them...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 6), reused 0 (delta 0)
Unpacking objects: 100% (16/16), done.
From https://aur.archlinux.org/rofi-greenclip
   4f19f42..0cc8e82  master     -> origin/master
?? Do you want to see the changes of rofi-greenclip? N/y: 
==> Making package: rofi-greenclip 3.0-0 (Wed 20 Jun 2018 13:13:14 BST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found greenclip
==> Validating source files with sha256sums...
    greenclip ... Passed
==> Extracting sources...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "rofi-greenclip"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding changelog file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: rofi-greenclip 3.0-0 (Wed 20 Jun 2018 13:13:15 BST)
==> Cleaning up...
2018-06-20 13:13:16,913 - classes - install - ERROR - package file of rofi-greenclip not available
```

Refer also to the comments of the package author: https://aur.archlinux.org/packages/rofi-greenclip/

**Comment by polygamma** [comment] 2018-06-20 12:17
Interesting... I can reproduce the problem, but I am currently preparing for exams, but I am definitely going to look into this and try to fix it, when I have time for it.

**Comment by polygamma** [comment] 2018-06-20 12:55
The current fix in development is not quite right, I missed something, nevertheless: I know what the problem is, will be fixed. It's the usage of `epoch=0`, `aurman` assumed, that `0:` is going to be part of the name of the resulting package, which in fact is wrong. `makepkg --packagelist` is the way to go here, I just have to make sure, that it is being implemented properly.

**Comment by polygamma** [comment] 2018-06-20 13:13
@eli-schwartz - what is the foolproof way of finding out, which package to pass to `pacman -U` from the build directory? e.g. I want to install `pacman-git`, `makepkg --packagelist` yields: 

```
[jonny@jonny-arch-pc pacman-git]$ makepkg --packagelist
/home/jonny/.cache/aurman/pacman-git/pacman-git-5.1.0.r19.g0d6e82d3-1-x86_64.pkg.tar
/home/jonny/.cache/aurman/pacman-git/pacman-git-debug-5.1.0.r19.g0d6e82d3-1-x86_64.pkg.tar
```

Hence there are two choices, how to detect the correct package to install? I had the assumption: package name + `-` + package version + `-` + architecture + PKGEXT

The problem is, that I assumed the version to be `0:3.0-0` because of `epoch=0`. What can I do, to implement this without any mistakes?

**Comment by eli-schwartz** [comment] 2018-06-20 14:52
`makepkg --packagelist` should generate a newline-separated list of candidate package files, following the assumption that the same /etc/makepkg.conf and user makepkg.conf are used both times (and likewise for shell environment variables which makepkg respects).

It will list all split packages, and in the event that debug is enabled in either the PKGBUILD or the current makepkg.conf, it will list the debug package too. (There is currently a bug, fixed in master with [this commit](https://git.archlinux.org/pacman.git/commit/?id=0d6e82d3748653a2b61ea34b940011ef97350768), which makes it print the debug packages per-pkgname instead of per-pkgbase.)

My motivation in providing packagelist in its current format is that downstream consumers of makepkg can use --packagelist for everything, and install each file that exists (since debug packages will only exist if the strip stage was able to find files to strip which is, um, generally not the case for arch=(any) packages or ones which package prebuilt binaries which are pre-stripped, and makepkg itself determines whether to create a debug package by checking to see if the debug package's `$pkgdir` contains files, skipping it otherwise).

Manual filtering by the prefix of the last filepath component (`os.path.split()[1]`) could be used to support installing only part of a split package (or to skip installing the debug package). The only subcomponents of the last filepath component which can contain "-" are the $pkgname and, I suppose, the $PKGEXT, so it's quite stable to check the pkgname of each resulting --packagelist filepath.

(Now I wonder if I should add linting checks to ensure the $PKGEXT does not contain "-" in it, just to guarantee even more stability.)

**Comment by polygamma** [comment] 2018-06-20 15:00
Thanks, https://github.com/polygamma/aurman/commit/8a7a00bf20e2035ab352e424c0fbb9114c2987d3 and https://github.com/polygamma/aurman/commit/fdeaecb739602d361468e44a40e4264bcc20b754 should do it then.

**Comment by polygamma** [comment] 2018-06-20 15:47
@SamHH - you may install `aurman-git` to check if everything works as expected.

**Comment by polygamma** [comment] 2018-06-20 18:34
`aurman 2.13.1` includes the fix.

**Comment by SamHH** [comment] 2018-06-20 20:54
Works perfectly, many thanks! :smile:
