### ISSUE TITLE
Hangs on (nearly) any operation with no sign of error or termination

### ISSUE THREAD

**Issue by jsaalfeld** [polygamma/aurman#224] opened 2018-07-19 13:46 UTC
## Description
aurman just hangs. no matter of the input. I did my normal ```aurman -Syu``` routine and noticed that nothing happened. A new-line popped up but there was no output. I cannot reproduce this behaviour on my other machine, nor can I correlate it with an upgrade of something.

## Expected Behavior

A normal output on ```aurman -Syu```

## Current Behavior

It just shows a blank line and does nothing

## Possible Solution

I noticed, that the ```/var/lib/pacman/db.lck``` is set, but I don't know where to start looking for a solution, because I can't get no output from it. I tried verbose options and specifying a logfile, but everything still results in a blank new-line (except the -h option).

## Version of aurman you are using

First the aurman version from aur: 2.16.9
Now with the version from git, too: 2.16.9.r22.g3d85c86-1

## Steps to Reproduce

1. open console
2. type ```aurman -Syu```

## Running linux distribution

4.17.6-1-ARCH - i3 desktop manager - sakura terminal

**Comment by polygamma** [comment] 2018-07-19 14:36
What happens if you execute pacman?

**Comment by polygamma** [comment] 2018-07-19 14:59
I tried to reproduce this by setting the lock, but I do not get a hanging `aurman`.

```
[jonny@jonny-arch-pc ~]$ aurman -Syu
:: Synchronizing package databases...
error: failed to update core (unable to lock database)
error: failed to update extra (unable to lock database)
error: failed to update community (unable to lock database)
error: failed to update multilib (unable to lock database)
error: failed to update sublime-text (unable to lock database)
error: failed to synchronize all databases
2018-07-19 16:58:41,132 - wrappers - pacman - ERROR - pacman query ['sudo', 'pacman', '--sync', '--refresh'] failed
```

anyway: if you are sure, that there a no `pacman` instances running, try manually deleting the lock file and run `aurman` again.

**Comment by polygamma** [comment] 2018-07-19 15:05
Also: Does searching for packages `-Ss` work? If it does, please check if using `--skip_news` leads to working `-Syu`.

**Comment by polygamma** [comment] 2018-07-19 15:51
archlinux.org feed is now fetched with `python-requests`, you may install the latest `aurman-git` version as of now. If the feed is the problem, you'll get a stacktrace after 5 seconds of trying, unless you changed the timeout for the aur rpc requests

**Comment by jsaalfeld** [comment] 2018-07-20 08:53
Normal ```pacman``` command works just fine.

The ```-Ss``` produces also just a new line and no feedback.

I have the latest git version installed.

**Comment by polygamma** [comment] 2018-07-20 11:32
I do not really have any sensible idea what it could be then. Have you tried deleting the config and cache folder of aurman? I need to know at which point the execution stops, so could you add print statements to the main.py to narrow down where the problem lie

**Comment by polygamma** [comment] 2018-07-20 11:34
Or as an alternative: Run aurman with an debugger

**Comment by jsaalfeld** [comment] 2018-07-20 12:42
After I deleted the ```~/.cache/aurman``` and ran ```aurman``` again, I noticed a 

    [~/.cache/aurman](:|✔)% ls
    seen_news_ids

in that folder. I deleted that and ran

    aurman -Syu --skip_news

successfully!

**Comment by polygamma** [comment] 2018-07-20 12:44
Cannot be the problem, because `-Ss` failed, too and that is being executed before the news are touched. Can you force `aurman` to fail again, currently?

**Comment by jsaalfeld** [comment] 2018-07-20 13:39
The ```-Ss``` now doesn't fail anyome, even without ```--skip-news```

I can't force a fail anymore, unfortunately.

**Comment by polygamma** [comment] 2018-07-20 13:54
Interesting... Anyway: Closing this issue for now, since I cannot do anything by now. If the issue comes up again, just reopen this issue and post the contents of your `aurman config` and the files in the `aurman cache` folder. Since deleting those files resolved the issue, it probably was a parsing problem, whereas I do not really know why it ended in the stopping execution instead of a stacktrace...

**Closed by polygamma** 2018-07-20 13:54 UTC
Labels: question
