### ISSUE TITLE
REQUEST: Change location for file seen_news_ids

### ISSUE THREAD

**Issue by Krnlsoft** [polygamma/aurman#254] opened 2018-08-18 19:36 UTC
## Description
Change the location for file seen_news_ids

## Desired Behavior
I mount XDG_CACHE_HOME inside /tmp folder, the file seen_news_ids is wiped on every reboot,
I'd like it to be preserved.

## Current Behavior
Actually the file is stored inside the XDG_CACHE_HOME

## Possible Solution
Store the file seen_news_ids in XDG_DATA_HOME

I've read the following link to decider whether or not my request would be good or not:

https://specifications.freedesktop.org/basedir-spec/0.6/ar01s03.html

Not sure, so I'm just asking what you think about it,
I could fork the repo, but I don't like it,
I know that many people don't bother about this, since they don't optimize ssd and disk usage.
Another solution would be to move the content from /tmp/... in my home folder on logout,
and restore it on login, but I don't like it either.

## Version of `aurman` you are using
2.18-1

## Content of `aurman` config
Not relevant

## Steps to Reproduce
Configure the following config file and reboot or logout:

FILE /etc/profile.d/xdg_cache_home.sh
#!/bin/bash
export XDG_CACHE_HOME="/tmp/${USER}/.cache"

## Read the README
Yes

## Running linux distribution
Linux krnl 4.18.1-arch1-1-ARCH #1 SMP PREEMPT Wed Aug 15 21:11:55 UTC 2018 x86_64 GNU/Linux

Thanks for your time.

**Comment by polygamma** [comment] 2018-08-18 20:02
duplicate of https://github.com/polygamma/aurman/issues/235

**Closed by polygamma** 2018-08-18 20:02 UTC

**Comment by polygamma** [comment] 2018-08-18 23:10
Addition: If it's about the diskspace, you could also use `aurman -Sc --aur` to clear the cache folder of `aurman`. It does not delete files like the seen news file however.

**Comment by Krnlsoft** [comment] 2018-08-19 06:04
I decided to setup a symlink on login, thanks anyway!
