### ISSUE TITLE
Overzealous removals

### ISSUE THREAD

**Issue by CNG** [polygamma/aurman#67] opened 2018-04-15 21:41 UTC
## Description

I wanted to switch from freetype2 to freetype2-cleartype, which conflicts. I ran:

    aurman -S freetype2-cleartype

## Expected Behavior

`aurman` should walk me through removing freetype2 and installing freetype2-cleartype.

## Current Behavior

It looks like `aurman` wants to remove a whole bunch of packages that I don't want to remove, including my browser!

```
aurman -S freetype2-cleartype
~~ initializing aurman...
~~ calculating solutions...
:: The following 1 package(s) are getting installed:
   aur/freetype2-cleartype        /                    ->  2.9-2
:: The following 38 package(s) are getting removed:
   extra/baloo                    5.44.0-1             ->  /
   extra/baloo-widgets            17.12.3-1            ->  /
   extra/chromaprint              1.4.3-1              ->  /
   extra/digikam                  5.9.0-1              ->  /
   extra/dolphin                  17.12.3-1            ->  /
   extra/dolphin-plugins          17.12.3-1            ->  /
   community/electron             1.8.4-1              ->  /
   extra/ffmpeg                   1:3.4.2-2            ->  /
   extra/ffmpegthumbnailer        2.2.0-1              ->  /
   extra/ffmpegthumbs             17.12.3-1            ->  /
   extra/firefox                  59.0.2-2             ->  /
   extra/freetype2                2.9-2                ->  /
   extra/gst-libav                1.14.0-1             ->  /
   extra/gst-plugins-bad          1.14.0-2             ->  /
   community/guvcview             2.0.5-3              ->  /
   extra/gwenview                 17.12.3-2            ->  /
   community/handbrake            1.1.0-1              ->  /
   aur/insync-dolphin             1.3.12.36116-1       ->  /
   extra/kamoso                   3.2.4-1              ->  /
   extra/kfilemetadata            5.44.0-1             ->  /
   extra/libass                   0.14.0-1             ->  /
   extra/libbluray                1.0.2-1              ->  /
   aur/losslesscut                1.9.0-3              ->  /
   community/messengerfordesktop  2.0.9+42+g4e4d6f1-5  ->  /
   extra/mpd                      0.20.18-3            ->  /
   extra/mplayer                  38017-1              ->  /
   community/mpv                  1:0.27.2-1           ->  /
   extra/opencv                   3.4.1-2              ->  /
   extra/phonon-qt5-vlc           0.10.1-2             ->  /
   extra/plasma-desktop           5.12.4-2             ->  /
   extra/plasma-meta              5.12-1               ->  /
   extra/qt5-webengine            5.10.1-1             ->  /
   extra/qtav                     1.12.0-2             ->  /
   aur/qtcam-git                  r25.75bc420-1        ->  /
   aur/untrunc-git                r58.ec8e417-1        ->  /
   extra/vlc                      3.0.1-2              ->  /
   extra/x264                     2:152.20171224-1     ->  /
   extra/xine-lib                 1.2.9-3              ->  /
:: Package freetype2 will be removed due to a conflict with freetype2-cleartype
:: Dependency libfreetype.so=6-64 of package libass is not fulfilled
:: Dependency libfreetype.so=6-64 of package ffmpeg is not fulfilled
:: Dependency libfreetype.so=6-64 of package libbluray is not fulfilled
:: Dependency ffmpeg of package kfilemetadata is not fulfilled
:: Dependency ffmpeg of package gst-libav is not fulfilled
:: Dependency ffmpeg of package ffmpegthumbnailer is not fulfilled
:: Dependency libass of package handbrake is not fulfilled
:: Dependency ffmpeg of package qt5-webengine is not fulfilled
:: Dependency ffmpeg of package xine-lib is not fulfilled
:: Dependency ffmpeg of package electron is not fulfilled
:: Dependency ffmpeg of package qtav is not fulfilled
:: Dependency ffmpeg of package guvcview is not fulfilled
:: Dependency ffmpeg of package mplayer is not fulfilled
:: Dependency ffmpeg of package mpv is not fulfilled
:: Dependency ffmpeg of package vlc is not fulfilled
:: Dependency ffmpeg of package firefox is not fulfilled
:: Dependency libavcodec.so=57-64 of package x264 is not fulfilled
:: Dependency ffmpeg of package chromaprint is not fulfilled
:: Dependency ffmpeg of package mpd is not fulfilled
:: Dependency ffmpeg of package ffmpegthumbs is not fulfilled
:: Dependency ffmpeg of package qtcam-git is not fulfilled
:: Dependency ffmpeg of package losslesscut is not fulfilled
:: Dependency ffmpeg of package untrunc-git is not fulfilled
:: Dependency xine-lib of package opencv is not fulfilled
:: Dependency vlc of package phonon-qt5-vlc is not fulfilled
:: Dependency electron of package messengerfordesktop is not fulfilled
:: Dependency kfilemetadata of package baloo is not fulfilled
:: Dependency chromaprint of package gst-plugins-bad is not fulfilled
:: Dependency qtav of package digikam is not fulfilled
:: Dependency gst-plugins-bad of package kamoso is not fulfilled
:: Dependency baloo of package gwenview is not fulfilled
:: Dependency baloo of package plasma-desktop is not fulfilled
:: Dependency baloo of package baloo-widgets is not fulfilled
:: Dependency baloo-widgets of package dolphin is not fulfilled
:: Dependency plasma-desktop of package plasma-meta is not fulfilled
:: Dependency dolphin of package dolphin-plugins is not fulfilled
:: Dependency dolphin of package insync-dolphin is not fulfilled
?? Do you want to continue? Y/n: n
```

## Possible Solution

I am not sure how these are all being selected, but it looks like `aurman` is trying to recursively remove everything that depends on `libfreetype.so` even though it is provided by the package I am trying to install. I tried the same operation but with `yaourt` instead of `aurman`, and that seemed to work as expected, only removing the conflicting freetype2 package:

```
loading packages...
resolving dependencies...
looking for conflicting packages...
:: freetype2-cleartype and freetype2 are in conflict. Remove freetype2? [y/N] y
Packages (2) freetype2-2.9-2 [removal]  freetype2-cleartype-2.9-2
Total Installed Size:  1.97 MiB
Net Upgrade Size:      0.00 MiB
```

## Steps to Reproduce

I think repro steps would depend on all the packages I have installed, which I can provide if desired.

**Comment by polygamma** [comment] 2018-04-15 21:52
Your question is being answered in the FAQ of aurman in the README.md

**Comment by polygamma** [comment] 2018-04-15 22:08
addition: but since these .so problems arise quite often, i am going to add a command line flag which leads to ignoring the exact versions of needed .so files

**Comment by CNG** [comment] 2018-04-16 00:34
Ah, missed that; and I see your point, though I wonder if it could be made more clear in the command output to reflect that the packages "may be removed" not "will be removed".

**Comment by polygamma** [comment] 2018-04-16 07:15
do you have a concrete suggestion for a better output message, which should not be too long, but still makes clear, that the packages "may" be removed? Only changing "will" to "may" would be too subtle, i guess

**Comment by actionless** [comment] 2018-04-17 00:40
> the pkgbuild of freetype2-cleartype does not provide the version of libfreetype.so, in my opinion all aur helpers which do not complain do something wrong.

```
$ makepkg
$ sudo pacman --upgrade ./freetype2-cleartype-2.9-2-x86_64.pkg.tar
loading packages...
resolving dependencies...
looking for conflicting packages...
:: freetype2-cleartype and freetype2 are in conflict. Remove freetype2? [y/N] y

Package (2)          Old Version  New Version  Net Change

freetype2            2.9-2                      -1.97 MiB
freetype2-cleartype               2.9-2          2.03 MiB

Total Installed Size:  2.03 MiB
Net Upgrade Size:      0.06 MiB

:: Proceed with installation? [Y/n]
```

**Comment by polygamma** [comment] 2018-04-17 06:17
so? what are you trying to tell us?

**Comment by actionless** [comment] 2018-04-17 11:34
you behaving different than pacman and claiming what whoever behave the same -- doing it wrong

**Comment by actionless** [comment] 2018-04-17 11:38
>  but it is about the pkgbuild, before building the package, the versions are not known

ok, that makes more sense, thanks for the explanation

**Comment by polygamma** [comment] 2018-04-17 12:16
aurman is not behaving different. you should get your facts right. pacman has the concrete information about the version, since the package is already built, aurman has not

**Comment by polygamma** [comment] 2018-04-17 13:51
sure, one could be optimistic first, but imagine the following: You want to install package A, and A depends on B and a specific .so file. B provides the .so, but does not list the exact version. Also does B depend on 100 other packages. You install 100 packages, build B and see that the .so is being provided in the wrong version, so you installed 100 packages for nothing. So aurman assumes: "If it's not sure, we assume it's not possible". The PKGBUILDs could just provide the version of the .so, and everything would be fine, so I really think the PKGBUILDs should change, and aur helpers shouldn't be too optimistic.

**Comment by actionless** [comment] 2018-04-17 16:50
> so you installed 100 packages for nothing

do you mean by this the amount of time spent for building 100 packages or you literally speaking about installing them and have dangling after unresolved dep? the second shouldn't be possible

**Comment by polygamma** [comment] 2018-04-17 16:56
they have been installed for nothing because you wanted to install A, but have not been able to install A

**Comment by actionless** [comment] 2018-04-17 17:41
but they should be removed in such case,
for example if during `makepkg -fsri` build step will fail, already installed deps will be removed. or you removing installed makedeps separately?

**Comment by polygamma** [comment] 2018-04-17 17:59
I do not see your point, again. You still installed them for nothing

**Comment by actionless** [comment] 2018-04-17 18:28
you installed them for building, not for nothing

i'd better ask which exactly part of the build process is generating that version for a `.so`, mb it can be executed without running the full build

**Comment by polygamma** [comment] 2018-04-17 18:50
please not

**Comment by rmarquis** [comment] 2018-04-18 09:26
libreetype.so is a provider, provider don't have to be versioned, and aurman default behaviour is different from pacman.

**Comment by polygamma** [comment] 2018-04-18 09:31
Sorry, I do not get what you are saying. I already gave an example why unlisted versions are a problem and besides that is the aurman behavior not even comparable to the behavior of pacman, since the situation for pacman, not knowing a version of an so file, does never arise since pacman installs built packages, where the so versions are known. e. g. an expac -S query for ffmpeg lists the provided so versions, not just the so files without versions

**Comment by rmarquis** [comment] 2018-04-18 09:34
You are simply overthinking the problem while you have to let user deal with it as this is a constraint brought by pacman/makepkg/PKGBUILD/rolling release design. The issue is with aurman, not other helpers, and that is why the prompt of aurman is dubious here.

**Comment by polygamma** [comment] 2018-04-18 09:37
Where does aurman NOT let the user deal with it? aurman checks the given information, and if a result is not 100% logically deducible, the assumption is: "not possible"
the user HAS to think about the given situation and handle it manually

**Comment by rmarquis** [comment] 2018-04-18 09:41
As I said: overthinking here. Installing `freetype2-cleartype` leads to removal of packages in the prompt, that are, in fact, not going to be removed. This is a "feature" of aurman, but to me it is is a bug.

**Comment by polygamma** [comment] 2018-04-18 09:43
Okay, then we simply define "feature" and "bug" differently in this situation and that's fine for me. Since I want to use aurman as aur helper, not seeing those prompts would be a "bug" from my point of view, hence this "feature" (or "bug") exists. But as I have written in the beginning of this issue: I am not happy with the current prompt, since the "possible not removal" is not made clear enough, hence I asked for a suggestion for a better prompt, but until now I have not got any suggestions

**Comment by rmarquis** [comment] 2018-04-18 10:01
Here is where I feel this is an issue:

> What you should do: Contact the maintainer of the relevant packages and ask to append the explicit versions of the files being provided.

Versioned dependencies are very rarely required, and most of the time are absolutely unnecessary on a rolling release. By requesting to add them upstream, you add an additional layer of complexity while the "correct" thing to do is to treat non-versioned dependencies as fulfilling any requirement instead of none. Catch the eventual pacman errors when building/installing and then suggest to add the (now required) versioned info upstream.

> hence I asked for a suggestion for a better prompt, but until now I have not got any suggestions

The actual prompt doesn't bring any information apart from "there might be a tiny chance of an issue, but we can't know that before it eventually happen." And in case it happens, pacman would fail instead of removing that list of packages. Honestly, the current prompt is better replaced by a line in the man page.

**Comment by polygamma** [comment] 2018-04-18 14:17
> By requesting to add them upstream, you add an additional layer of complexity while the "correct" thing to do is to treat non-versioned dependencies as fulfilling any requirement instead of none. 

aurman is doing exactly that. https://github.com/polygamma/aurman/blob/master/src/aurman/classes.py#L1274

this whole issue is about versioned dependencies, with the problem of not knowing the exact versions of the providers.

**Comment by polygamma** [comment] 2018-04-18 16:41
see: https://github.com/polygamma/aurman/commit/b7c907494e67d80d19eebd0165a6985a5e3f5e0e

**Comment by polygamma** [comment] 2018-04-18 17:16
see also: https://github.com/polygamma/aurman/commit/efeec073fbb100db7c16f1627f4e108e08481aa2

**Comment by polygamma** [comment] 2018-04-18 17:28
@CNG - is this command line flag achieving the behavior you are expecting?

**Comment by AladW** [comment] 2018-04-18 21:07
The only way this approach of "make noise if versioned information is missing" is relevant when the user did a [partial upgrade](https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported), or am I missing something?

**Comment by polygamma** [comment] 2018-04-18 21:10
It has not much to do with partial upgrades, it's really only about listing the versions in PKGBUILDs in the AUR. It's also not relevant for repo packages, since the versions are ALWAYS known, when packages are built, and repo packages are built by definition.

**Comment by AladW** [comment] 2018-04-18 21:14
Well, I don't see how you're going to convince anyone to add this information to PKGBUILDs, since 1) it is automatically added by `makepkg` 2) it hardly matters on a rolling release - the vast majority of repo packages lack versioned dependencies, and in the unlikely event that they do _and_ it turns out (on build) that the AUR package conflicts with said versioned dependencies, it's either broken or outdated and it should be removed from the AUR.

**Comment by polygamma** [comment] 2018-04-18 21:20
As I have mentioned before, *in my opinion* the strict behavior should be the default, and hence it is the default. It really is about opinions at that point, and nothing else. It also is not comparable to pacman behavior since this problem does not arise for pacman. Now there is the flag to disable this behavior, and I think I'll stick with it. All in all, and I know many people do not like when I say something like this, aurman is my aur helper, and hence it will *always* be written in the way I want aurman to be. Everybody may fork aurman, do whatever he wants with it, or just use aliases to change behavior, use the config etc.

**Comment by AladW** [comment] 2018-04-18 21:28
Well, I guess the "my way or the highway" approach isa  double-edged sword; on the one hand it prevents the helper from getting too popular (which is a good thing in the helper world), on the other hand it might scare off potential contributors. But if you already consider `aurman` complete as a project that might not be relevant to you. 

Just my 2 cents - all of us are doing this in their free time and as you say, the code is free to modify if someone doesn't like it.

**Comment by polygamma** [comment] 2018-04-18 21:42
I definitely do not follow a "my way or the highway" approach, and I am always grateful for feedback, really, but this issue is no bug, it's about a matter of taste, which things should be turned on by default. Since there exists an option to change this behavior, everybody may change it. Hence it comes down to: User has to read the readme, configure aurman as he wants, and that's it. And tbh: Not getting too popular really is something nice. I'm already annoyed by some "bug reports", which did not even try to make an effort to really explain the bug. Or some absurd feature requests... But since people like you, @rmarquis or @ChuckDaniels87 are around, who helped me *a lot*, I'll definitely keep aurman on GitHub, be open for bug reports, feature requests, etc. 

Also I think `aurman` really is quite "complete", there are a few features, which will be added after the semester of university is over, besides that bugs will always be fixed, but all in all I am really happy with aurman. I'm using it for a few months now, this helper does what I want, in a way I want an aur helper to be, and that's fine. I started programming aurman in the first place, because @rmarquis abandoned pacaur, and I did not like the other aur helpers, I still don't. One exception: aurutils, but for me that was not what I wanted.

**Comment by CNG** [comment] 2018-04-19 04:51
Sorry for falling off; I am mostly only able to poke at this on the weekends. I will review as soon as I can.

**Comment by polygamma** [comment] 2018-04-23 10:59
I am closing this for now, if the new flag does not resolve the problem for you, just comment again in this issue

**Closed by polygamma** 2018-04-23 10:59 UTC
Labels: enhancement

**Comment by polygamma** [comment] 2018-05-21 20:29
the makepkg thing is kinda persistent, since your architecture won't simply change. this should only be used if needed, hence command line only
